//data class Post (val id: Int=0,
//                 val ownerId: Int=0,
//                 val fromId: Int=0,
//                 val createdBy: Int=0,
//                 val date: Int=0,
//                 var text: String="",
//                 val replyOwnerId: Int=0,
//                 val replyPostId: Int=0,
//                 val friendsOnly: Boolean=false,
//                 val comments: Comments,
//                 val copyright: String="",
//                 val likes: Likes,
//                 val repost: Reposts,
//) {
//}